version: '3.1'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: localdev
      POSTGRES_PASSWORD: localdev
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
