name: App Engine Deploy

on:
  workflow_dispatch:

jobs:
  app-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v0.5.0"
        with:
          working_directory: "../.."
          deliverables: "src/main/appengine"

      - id: "test"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
